name: quizai
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_easyloading: ^3.0.5
  loader_overlay: ^2.1.0
  google_fonts: ^4.0.3
  simple_animations: ^5.0.0+3
  mask_text_input_formatter: ^2.4.0
  otp_text_field: ^1.1.3
  modal_bottom_sheet: ^2.1.2
  flutter_svg: ^2.0.0+1
  bottom_bar_page_transition: ^2.0.0
  share: ^2.0.4
  back_button_interceptor: ^6.0.2
  dotted_border: ^2.0.0+3
  image_picker: ^0.8.6+1
  infinite_scroll_pagination: ^3.2.0
  flutter_spinkit: ^5.1.0
  intl: ^0.18.0
  masonry_grid: ^1.0.0
  flutter_masked_text2: ^0.9.1
  responsive_framework: ^0.2.0
  ndialog: ^4.3.0
  table_calendar: ^3.0.9
  file_picker: ^5.2.5
  pull_to_refresh: ^2.0.0
  grouped_list: ^5.1.2
  emoji_picker_flutter: ^1.5.2
  any_link_preview: ^3.0.0
  scrollable_positioned_list: ^0.3.5
  path_provider: ^2.0.12
  get: ^4.6.5
  flutter_advanced_drawer: ^1.3.4


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  retrofit_generator: ^4.2.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  built_value_generator: ^8.4.3
  flutter_launcher_icons: ^0.11.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
